package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Manager;

public interface ManagerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MANAGER
     *
     * @mbg.generated Mon Mar 06 18:32:26 EET 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MANAGER
     *
     * @mbg.generated Mon Mar 06 18:32:26 EET 2023
     */
    int insert(Manager record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MANAGER
     *
     * @mbg.generated Mon Mar 06 18:32:26 EET 2023
     */
    Manager selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MANAGER
     *
     * @mbg.generated Mon Mar 06 18:32:26 EET 2023
     */
    List<Manager> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MANAGER
     *
     * @mbg.generated Mon Mar 06 18:32:26 EET 2023
     */
    int updateByPrimaryKey(Manager record);
}