package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Store;

public interface StoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STORE
     *
     * @mbg.generated Mon Mar 06 18:32:26 EET 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STORE
     *
     * @mbg.generated Mon Mar 06 18:32:26 EET 2023
     */
    int insert(Store record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STORE
     *
     * @mbg.generated Mon Mar 06 18:32:26 EET 2023
     */
    Store selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STORE
     *
     * @mbg.generated Mon Mar 06 18:32:26 EET 2023
     */
    List<Store> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STORE
     *
     * @mbg.generated Mon Mar 06 18:32:26 EET 2023
     */
    int updateByPrimaryKey(Store record);
}