package lt.vu.mybatis.model;

public class Manager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MANAGER.ID
     *
     * @mbg.generated Mon Mar 06 18:32:26 EET 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MANAGER.NAME
     *
     * @mbg.generated Mon Mar 06 18:32:26 EET 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MANAGER.VERSION
     *
     * @mbg.generated Mon Mar 06 18:32:26 EET 2023
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MANAGER.STORE_ID
     *
     * @mbg.generated Mon Mar 06 18:32:26 EET 2023
     */
    private Integer storeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MANAGER.ID
     *
     * @return the value of PUBLIC.MANAGER.ID
     *
     * @mbg.generated Mon Mar 06 18:32:26 EET 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MANAGER.ID
     *
     * @param id the value for PUBLIC.MANAGER.ID
     *
     * @mbg.generated Mon Mar 06 18:32:26 EET 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MANAGER.NAME
     *
     * @return the value of PUBLIC.MANAGER.NAME
     *
     * @mbg.generated Mon Mar 06 18:32:26 EET 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MANAGER.NAME
     *
     * @param name the value for PUBLIC.MANAGER.NAME
     *
     * @mbg.generated Mon Mar 06 18:32:26 EET 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MANAGER.VERSION
     *
     * @return the value of PUBLIC.MANAGER.VERSION
     *
     * @mbg.generated Mon Mar 06 18:32:26 EET 2023
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MANAGER.VERSION
     *
     * @param version the value for PUBLIC.MANAGER.VERSION
     *
     * @mbg.generated Mon Mar 06 18:32:26 EET 2023
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MANAGER.STORE_ID
     *
     * @return the value of PUBLIC.MANAGER.STORE_ID
     *
     * @mbg.generated Mon Mar 06 18:32:26 EET 2023
     */
    public Integer getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MANAGER.STORE_ID
     *
     * @param storeId the value for PUBLIC.MANAGER.STORE_ID
     *
     * @mbg.generated Mon Mar 06 18:32:26 EET 2023
     */
    public void setStoreId(Integer storeId) {
        this.storeId = storeId;
    }
}