package lt.vu.mybatis.model;

public class Store {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STORE.ID
     *
     * @mbg.generated Mon Mar 06 18:32:26 EET 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STORE.ADDRESS
     *
     * @mbg.generated Mon Mar 06 18:32:26 EET 2023
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STORE.VERSION
     *
     * @mbg.generated Mon Mar 06 18:32:26 EET 2023
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STORE.MANAGER_ID
     *
     * @mbg.generated Mon Mar 06 18:32:26 EET 2023
     */
    private Integer managerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STORE.ID
     *
     * @return the value of PUBLIC.STORE.ID
     *
     * @mbg.generated Mon Mar 06 18:32:26 EET 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STORE.ID
     *
     * @param id the value for PUBLIC.STORE.ID
     *
     * @mbg.generated Mon Mar 06 18:32:26 EET 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STORE.ADDRESS
     *
     * @return the value of PUBLIC.STORE.ADDRESS
     *
     * @mbg.generated Mon Mar 06 18:32:26 EET 2023
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STORE.ADDRESS
     *
     * @param address the value for PUBLIC.STORE.ADDRESS
     *
     * @mbg.generated Mon Mar 06 18:32:26 EET 2023
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STORE.VERSION
     *
     * @return the value of PUBLIC.STORE.VERSION
     *
     * @mbg.generated Mon Mar 06 18:32:26 EET 2023
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STORE.VERSION
     *
     * @param version the value for PUBLIC.STORE.VERSION
     *
     * @mbg.generated Mon Mar 06 18:32:26 EET 2023
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STORE.MANAGER_ID
     *
     * @return the value of PUBLIC.STORE.MANAGER_ID
     *
     * @mbg.generated Mon Mar 06 18:32:26 EET 2023
     */
    public Integer getManagerId() {
        return managerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STORE.MANAGER_ID
     *
     * @param managerId the value for PUBLIC.STORE.MANAGER_ID
     *
     * @mbg.generated Mon Mar 06 18:32:26 EET 2023
     */
    public void setManagerId(Integer managerId) {
        this.managerId = managerId;
    }
}